### ISSUE TITLE
Add support for Excel 2007 xlsx format

### ISSUE THREAD

**Issue by dumblob** [manns/pyspread#119]
*xlrd* and *xlwt* are not being developed any more and they don't support the currently most widespread format - Excel 2007 *xlsx*. Would it be possible to add support for the *xlsx* format using [*openpyxl*](https://github.com/Polyconseil/openpyxl) as recommended on http://www.python-excel.org/ ?

If it's too complicated, I wouldn't be afraid of abandoning the *xlrd*/*xlwt* backend completely in favour of only supporting *xlsx* (there are plenty of reasonably functional converters to *xlsx*, so I wouldn't worry about old *xls* files). The support for *ods* would also be nice-to-have, but can be added later.

It's really a shame, that such lean, but very powerful tool can't be currently used in most cases where it would shine (i.e. in existing *xlsx* document hell in organizations of all sizes).

**Comment by manns** [comment]
I agree that switching to openpyxl would improve pyspread. Not having done so yet is mainly a time issue on my side. 

However, if you would help this would speed up things. I have made it as easy as possible to add or change interfaces.  You would just change the [interface file] (https://github.com/manns/pyspread/blob/master/pyspread/src/interfaces/xls.py) and the respective [interface test file] (https://github.com/manns/pyspread/blob/master/pyspread/src/interfaces/test/test_xls.py).

Interface levels for pyspread should be considered threefold:
1. Convert cell content
2. Convert cell content and cell layout (the current state of the xls interface)
3. Convert cell content, cell layout and cell functions

I recommend starting with level 1 when switching to openpyxl.
However, if you want to seriously get away from xlsx document hell you need level 3 because otherwise each formula has to be revised by hand, which from my experience noone will do in a company environment. [pycel] (https://github.com/dgorissen/pycel) might be a good start for this.

**Comment by manns** [comment]
I close this issue since basic xlsx support has been added.
