### ISSUE TITLE
Python3 port?

### ISSUE THREAD

**Issue by yuvallanger** [manns/pyspread#137]

**Comment by manns** [comment]
I had started working on a Python3 port about a year ago but I ran into several issues with wxPython Phoenix. You can find the result in the python3 branch. Note that many things including charts are not functional.

Just now would be a good opportunity to start again because v 1.1 just has been released.
The only problem is time.

**Comment by Yatekii** [comment]
I would like to help with porting it to 3.x as I think 2.x is unacceptable for any nice Python app ... have you ever considered using pyQt5 instead of wx?

**Comment by manns** [comment]
@Yatekii: Thank you for helping with the 2to3 transition.

I have been considering pyQT. I even had initially tried it out when starting pyspread. In the end, QT was not free software back then, the wx approach that employs native widgets on each platform is great and finally, the wx.Grid component was much better than anything that I found in pyQT.
Now switching the GUI framework is difficult because most of the code is wx related. The core is not dependent on wx but most of the functionality is GUI related. One could do it though and it would be a good moment indeed. But I certainly cannot put my time into it.

Therefore, I have waited for wxPython Phoenix. Right now is the first time that I feel good about the builds. Currently on Python3, Pyspread (the python3 branch) starts to the following screen:

![pyspread on python3](https://cloud.githubusercontent.com/assets/605892/23478693/6557dfb4-fec2-11e6-9dd6-268a78c85b8d.png)

The reason, why the grid is not drawn is the following issue:
https://github.com/wxWidgets/Phoenix/issues/241

However, fixing this is only the start.

In order to start helping, please clone and compile Phoenix from github:
https://github.com/wxWidgets/Phoenix.git

I further suggest that we switch to the pyspread development mailing list:
pyspread-dev@gna.org

Martin

**Comment by manns** [comment]
Just an update:
The Python3 port needs PangoCairo to work with wxPython Phoenix. However, this does not seem to work (see Issue https://github.com/wxWidgets/Phoenix/issues/247)

**Comment by manns** [comment]
Another update:
I now am working on a pyqt5 based Python3 version of pyspread.
It is located in the top src folder of the python3 branch.
```bash
    $ checkout python3
    $ cd src
    $ pyspread.py

**Comment by pedromorgan** [comment]
@manns is there a TODO list for pyqt5, I'd like to help

**Comment by manns** [comment]
@pedromorgan 
Great that you ask. Please not that the GUI is a complete rewrite.
For Python3, I try to deviate as little as possible from pyqt5 standards, which should reduce and simplify the UI code.

I am using the to do list below for the Python3 port. It is not sorted for priority.
If you did category (3) tasks that would help a lot.

1) Closed tasks (incomplete)
 * File open and close
 * New file signing mechanism that does not rely on GPG
 * Cell formatting via toolbar and color dialogs
 * Cell rotation, justification and alignment
 * Merge cells
 * Preferences dialog
 * Quotation of cell content
 * Spell checker
 * Syntax highlighting
 * Image rendering in cells
 * About dialog

2) Active tasks
 * Matplotlib charts dialog and cell plotting
 * Matplotlib charts cell renderer

3) Open tasks
 * csv file import
 * csv file export
 * pdf file export
 * svg file export
 * Print framework
 * Undo & redo (via decorators)
 * Cut, Copy, copy results, paste, paste as
 * Select all
 * Find & Replace (via toolbar)
 * Sorting of cells (must not break the sheet this time -> X, Y, Z have to be adjusted)
 * Row, column and table insertion and deletion
 * Table sorting (via drag and drop in GUI and in menu)
 * Resize grid
 * Fullscreen functionality
 * Switching on and off of toolbars and panels (incomplete and broken, needs fix)
 * Toolbar individualization
 * Macro panel
 * Goto cell
 * Zoom in, out etc.
 * Cell refresh manual, periodic
 * Show frozen cells
 * Copy and paste cell formatting
 * Cell formatting font dialog
 * Freeze cell
 * Help browser
 * Dependencies dialog

4) Nice to have tasks that most likely will not be realized in pyspread 2.0
 * xls, xlsx import (must include cell code analysis and transfer this time to be useful)
 * odt import (must include cell code analysis and transfer this time to be useful)
 * Automated generation of cell references via mouse
 * Code introspection (worked poorly with jedi)

**Comment by pedromorgan** [comment]
@manns Some questions..

`Toolbar individualization` - What does this mean ?

`Help Browser` - I assume you mean inbuilt help as in doc/help ? Also these could be in markdown ?

**Comment by manns** [comment]
@pedromorgan I have added comments in the to do list

**Comment by pedromorgan** [comment]
I notice the repos is around 100meg atmo.. It might be worth "extracting" the python3 branch into a new repos imho, its kinda a rewrite ..

**Comment by manns** [comment]
@pedromorgan I have seem no need in creating a smaller repo, yet. It still performs quite well for me. Have you encountered any issues?

**Comment by pedromorgan** [comment]
@manns would be handy to chat..  https://gitter.im/pyspread/community

**Comment by eggonlea** [comment]
Hello, I just tried python3 branch (as I failed to have master branch run on Ubuntu 18.04 with python2.7, due to some pango/cairo module issue). It successfully launched with ./pyspread.sh. But there's no grid showing. And the console prints quite a few errors from wxPython instead of pyqt5. Am I using the wrong branch? Thanks!

`(base) ~/vobs/pyspread$ ./pyspread.sh 
16:12:50: Debug: Adding duplicate image handler for 'Windows bitmap file'
16:12:50: Debug: Adding duplicate image handler for 'Windows bitmap file'
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_grid_renderer.py", line 351, in Draw
    mdc, 0, 0, wx.COPY)
wx._core.wxAssertionError: C++ assertion "source && source->IsOk()" failed at /home/vagrant/wxPython-4.0.6/ext/wxWidgets/src/gtk/dc.cpp(142) in DoStretchBlit(): invalid source DC
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
Traceback (most recent call last):
  File "/srv/vobs/pyspread/pyspread/src/gui/_widgets.py", line 596, in OnDrawItem
    pangocairo_context.set_antialias(cairo.ANTIALIAS_SUBPIXEL)
AttributeError: 'Context' object has no attribute 'set_antialias'
`

**Comment by manns** [comment]
@eggonlea 

You need to cd into the src folder and run
python3 pyspread.py

**Comment by eggonlea** [comment]
@manns Cool~ Thanks. I didn't release that the qt version is in a separate folder.

Is the .pys compatible with the old python2.7 version? I failed to open the file saved before.

**Comment by manns** [comment]
@eggonlea It should be compatible even though there will be issues because the code is not translated from Python2 to Python3. However, the Python3 part is early alpha and not tested, yet.

**Comment by manns** [comment]
The Python3 port is on its way.
The development repo has moved to https://gitlab.com/pyspread/pyspread
I will close the issue, here.
