### ISSUE TITLE
Filetype is not determined properly upon open()

### ISSUE THREAD

**Issue by Yatekii** [manns/pyspread#139]
In ./src/gui/_main_widow.py line 820 the filetype automatically gets set to the default set filetype if the filetype is not changed in the open filedialog.

This feature sucks imho. I hate programs where I have to select a filetype. It is the job of the program to determine it properly from a randomly selected file or yield an error. This a general opinion on this topic.

Furthermore, on mac, this filetype selection select-box is missing (IDK why, it's there for the save dialog, but I feel like this is just a feature OSX does not offer (since it's useless as stated above) in general (I have never seen it)) but you can still select ALL files (as told, in OSX the fopen dialog generally behaves like this). This results in pyspread trying to open the file in the wrong format (default: pys) when the file is actually pysu.

I suggest removing "filetype": filetype from the attrs on line 829 so the open() function will properly determine the filetype from the ending.

It might also be worth a shot trying to open with all the file formats and try the next when one fails until all fail or one succeds.

If you see this as an issue as well I will gladly submit a pull request :)

**Comment by manns** [comment]
What I do not see is how a file type can be determined from its name - at least on Linux.
I am well aware that there are file type assumptions on Windows. I did not know about OS X.
This is the curse of multi-platform development.

In fact, we cannot rely on the file type in Linux. You fix may break current workflows for integrating pyspread with git.

In order to do it right, we need to rely on the magic bytes. Therefore, we could employ the python-magic module. However, I have read somewhere that this module works with Linux and Windows bit not with OS X.

Ultimately, we need to check individually:
1) pys files: Are bz2 compressed UTF-8 text files that have a specific start sequence [Pyspread save file version]
2) pysu files: Are UTF-8 text files that have a specific start sequence [Pyspread save file version]
3) xls files: Composite Document File V2 Document, Little Endian, Os: Windows, unsure how to pre-determine it
4) xlsx files: Zip archive data, which contains a file [Content_Types].xml that starts with 
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org
5) ods: OpenDocument Spreadsheet

If we implement this then we need to find a way of determining the file types for OS X as well.
Then we could also implement automagic addition of a file suffix when saving a file.
