### ISSUE TITLE
Insert table problem

### ISSUE THREAD

**Issue by ded0rg** [manns/pyspread#142]
Linux mint, latest version, pyspread 1.1 installed from source.

New file with 3 tables
editing table 2
insert table

table 1 contents over written and still only 3 tables.

try delete table
table contents deleted but table stays

Have I misunderstood something?
Any help appreciated

Thanks

Richard

PS insert rows and columns also fails

**Comment by manns** [comment]
I am not sure what the issue is.

I just have tried out the following using 1.1 under Debian:

1.  New files with a 1000, 100, 3 grid (i.e. with 3 tables)
2. Place 0 in cell [0,0,0], 1 in cell [0,0,1] and 2 in cell [0,0,3]
3. Go to table 2
4. select insert table

The result should be: 
 * The grid still has 3 tables
 * Table 2 is empty
 * Tables 0 and 1 are unchanged.

Is this the case?

Note that insert column, row or table just shifts the cells and does not change the grid size.
If you want to resize the grid, please use Edit -> Resize Grid

**Comment by ded0rg** [comment]
Thanks for that.  I had misunderstood how it worked.  I was expecting 'insert tbale' to ADD a table.  Failed to look at 'edit grid'.
My fault - sorry.
Richard
