### ISSUE TITLE
Replace Windows installer & fix website links now that Gna! has shut down

### ISSUE THREAD

**Issue by noahbrenner** [manns/pyspread#143]
Since gna.org [has shut down](https://en.wikipedia.org/wiki/Gna!), there are some dead links on [manns.github.io/pyspread](http://manns.github.io/pyspread/) including the windows installer. I would suggest replacing the installer by including it with the GitHub Releases downloads, though there are other good options too.

#### Home
- **Contact** section: All of the links and email addresses are under the gna.org domain

#### Contribute
- **How to help** section: The provided email address is pyspread-dev@gna.org
- **Submitting code** section: Same email as above

**Comment by manns** [comment]
Thank you for noticing.
The gna shoutdown came without any e-mail notice (at least not beyond my SPAM filter).

The good news is that I have backups for the Windows installer.
The bad news is that I have to set up new mailing lists etc. as well as a new backup site.
I hesitate using the github site for everything because if that disappears as well then there is no communication channel left.

I will remove the dead links right now and reestablish a new solution ASAP.

**Comment by manns** [comment]
I just have uploaded the Windows installer to github, and I have removed all the links to the mailing lists.

However, I keep this issue open because a long term solution is needed.

**Comment by manns** [comment]
E-Mail communication together with github seems to work well enough.
Therefore, I am not planning to set up another mailing list.
